### ISSUE TITLE
PHP Error on Login with admin User

### ISSUE THREAD

**Issue by moiri** [humdek-unibe-ch/sh-selfhelp#453]
Tue Feb 20 21:19:12.961084 2024] [php:error] [pid 9794] [client <IP>] PHP Fatal error:  Uncaught ErrorException: Trying to access array offset on value of type bool in selfhelp/server/service/UserInput.php:94

Stack trace:
```
#0  selfhelp/server/service/UserInput.php(94): exception_error_handler()
#1  selfhelp/server/service/UserInput.php(1072): UserInput->fetch_input_fields()
#2  selfhelp/server/service/Login.php(189): UserInput->get_input_fields()
#3  selfhelp/server/service/Login.php(269): Login->update_timestamp()
#4  selfhelp/server/component/style/login/LoginModel.php(76): Login->check_credentials()
#5  selfhelp/server/component/style/login/LoginController.php(52): LoginModel->check_login_credentials()
#6  selfhelp/server/component/style/login/LoginComponent.php(41): LoginController->__construct()
#7  selfhelp/server/component/style/StyleComponent.php(102): LoginComponent->__construct()
#8  selfhelp/server/component/style/StyleModel.php(227): StyleComponent->__construct()
#9  selfhelp/server/component/style/StyleModel.php(134): StyleModel->loadChildren()
#10 selfhelp/server/component/style/StyleComponent.php(95): StyleModel->__construct()
#11 selfhelp/server/page/SectionPage.php(59): StyleComponent->__construct()
#12 selfhelp/Selfhelp.php(223): SectionPage->__construct()
#13 selfhelp/Selfhelp.php(62): Selfhelp->web_call()
#14 selfhelp/Selfhelp.php(42): Selfhelp->init()
#15 selfhelp/index.php(25): Selfhelp->__construct()
#16 {main}
  thrown in selfhelp/server/service/UserInput.php on line 94
```

I was able to solve this by assigning the admin user a gender.

**Comment by Kodzhabashev** [comment]
fixed in v6.11.0
